export const continentMap = {
    // --- AFRIQUE ---
    'Algeria': 'Afrique',
    'Angola': 'Afrique',
    'Benin': 'Afrique',
    'Botswana': 'Afrique',
    'Burkina Faso': 'Afrique',
    'Burundi': 'Afrique',
    'Cabo Verde': 'Afrique',
    'Cameroon': 'Afrique',
    'Central African Republic': 'Afrique',
    'Chad': 'Afrique',
    'Comoros': 'Afrique',
    'Congo': 'Afrique',
    'Côte d\'Ivoire': 'Afrique',
    'D.R. of the Congo': 'Afrique',
    'Djibouti': 'Afrique',
    'Egypt': 'Afrique',
    'Equatorial Guinea': 'Afrique',
    'Eritrea': 'Afrique',
    'Eswatini': 'Afrique',
    'Ethiopia': 'Afrique',
    'Gabon': 'Afrique',
    'Gambia': 'Afrique',
    'Ghana': 'Afrique',
    'Guinea': 'Afrique',
    'Guinea-Bissau': 'Afrique',
    'Kenya': 'Afrique',
    'Lesotho': 'Afrique',
    'Liberia': 'Afrique',
    'Libya': 'Afrique',
    'Madagascar': 'Afrique',
    'Malawi': 'Afrique',
    'Mali': 'Afrique',
    'Mauritania': 'Afrique',
    'Mauritius': 'Afrique',
    'Morocco': 'Afrique',
    'Mozambique': 'Afrique',
    'Namibia': 'Afrique',
    'Niger': 'Afrique',
    'Nigeria': 'Afrique',
    'Rwanda': 'Afrique',
    'Sao Tome and Principe': 'Afrique',
    'Senegal': 'Afrique',
    'Seychelles': 'Afrique',
    'Sierra Leone': 'Afrique',
    'Somalia': 'Afrique',
    'South Africa': 'Afrique',
    'South Sudan': 'Afrique',
    'Sudan': 'Afrique',
    'Togo': 'Afrique',
    'Tunisia': 'Afrique',
    'U.R. of Tanzania: Mainland': 'Afrique',
    'Uganda': 'Afrique',
    'Zambia': 'Afrique',
    'Zanzibar': 'Afrique',
    'Zimbabwe': 'Afrique',
  
    // --- AMÉRIQUES ---
    'Anguilla': 'Amériques',
    'Antigua and Barbuda': 'Amériques',
    'Argentina': 'Amériques',
    'Aruba': 'Amériques',
    'Bahamas': 'Amériques',
    'Barbados': 'Amériques',
    'Belize': 'Amériques',
    'Bermuda': 'Amériques',
    'Bolivia (Plurinational State of)': 'Amériques',
    'Brazil': 'Amériques',
    'British Virgin Islands': 'Amériques',
    'Canada': 'Amériques',
    'Cayman Islands': 'Amériques',
    'Chile': 'Amériques',
    'Colombia': 'Amériques',
    'Costa Rica': 'Amériques',
    'Cuba': 'Amériques',
    'Curaçao': 'Amériques',
    'Dominica': 'Amériques',
    'Dominican Republic': 'Amériques',
    'Ecuador': 'Amériques',
    'El Salvador': 'Amériques',
    'Greenland': 'Amériques',
    'Grenada': 'Amériques',
    'Guatemala': 'Amériques',
    'Guyana': 'Amériques',
    'Haiti': 'Amériques',
    'Honduras': 'Amériques',
    'Jamaica': 'Amériques',
    'Mexico': 'Amériques',
    'Montserrat': 'Amériques',
    'Nicaragua': 'Amériques',
    'Panama': 'Amériques',
    'Paraguay': 'Amériques',
    'Peru': 'Amériques',
    'Puerto Rico': 'Amériques',
    'Saint Kitts and Nevis': 'Amériques',
    'Saint Lucia': 'Amériques',
    'Sint Maarten (Dutch part)': 'Amériques',
    'St. Vincent and the Grenadines': 'Amériques',
    'Suriname': 'Amériques',
    'Trinidad and Tobago': 'Amériques',
    'Turks and Caicos Islands': 'Amériques',
    'United States of America': 'Amériques',
    'Uruguay': 'Amériques',
    'Venezuela (Bolivarian Republic of)': 'Amériques',
  
    // --- ASIE ---
    'Afghanistan': 'Asie',
    'Armenia': 'Asie',
    'Azerbaijan': 'Asie',
    'Bahrain': 'Asie',
    'Bangladesh': 'Asie',
    'Bhutan': 'Asie',
    'Brunei Darussalam': 'Asie',
    'Cambodia': 'Asie',
    'China': 'Asie',
    'China, Hong Kong SAR': 'Asie',
    'China, Macao SAR': 'Asie',
    'Cyprus': 'Asie',
    'D.P.R. of Korea': 'Asie',
    'Georgia': 'Asie',
    'India': 'Asie',
    'Indonesia': 'Asie',
    'Iran (Islamic Republic of)': 'Asie',
    'Iraq': 'Asie',
    'Israel': 'Asie',
    'Japan': 'Asie',
    'Jordan': 'Asie',
    'Kazakhstan': 'Asie',
    'Kuwait': 'Asie',
    'Kyrgyzstan': 'Asie',
    'Lao People\'s DR': 'Asie',
    'Lebanon': 'Asie',
    'Malaysia': 'Asie',
    'Maldives': 'Asie',
    'Mongolia': 'Asie',
    'Myanmar': 'Asie',
    'Nepal': 'Asie',
    'Oman': 'Asie',
    'Pakistan': 'Asie',
    'Philippines': 'Asie',
    'Qatar': 'Asie',
    'Republic of Korea': 'Asie',
    'Saudi Arabia': 'Asie',
    'Singapore': 'Asie',
    'Sri Lanka': 'Asie',
    'State of Palestine': 'Asie',
    'Syrian Arab Republic': 'Asie',
    'Tajikistan': 'Asie',
    'Thailand': 'Asie',
    'Timor-Leste': 'Asie',
    'Türkiye': 'Asie',
    'Turkmenistan': 'Asie',
    'United Arab Emirates': 'Asie',
    'Uzbekistan': 'Asie',
    'Vietnam': 'Asie',
    'Yemen': 'Asie',
  
    // --- EUROPE ---
    'Albania': 'Europe',
    'Andorra': 'Europe',
    'Austria': 'Europe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Bosnia and Herzegovina': 'Europe',
    'Bulgaria': 'Europe',
    'Croatia': 'Europe',
    'Czechia': 'Europe',
    'Denmark': 'Europe',
    'Estonia': 'Europe',
    'Finland': 'Europe',
    'France': 'Europe',
    'Germany': 'Europe',
    'Greece': 'Europe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'Ireland': 'Europe',
    'Italy': 'Europe',
    'Kosovo': 'Europe',
    'Latvia': 'Europe',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Malta': 'Europe',
    'Monaco': 'Europe',
    'Montenegro': 'Europe',
    'Netherlands': 'Europe',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Republic of Moldova': 'Europe',
    'Romania': 'Europe',
    'Russia': 'Europe',
    'San Marino': 'Europe',
    'Serbia': 'Europe',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Spain': 'Europe',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Ukraine': 'Europe',
    'United Kingdom': 'Europe',
  
    // --- OCÉANIE ---
    'Australia': 'Océanie',
    'Cook Islands': 'Océanie',
    'Fiji': 'Océanie',
    'French Polynesia': 'Océanie',
    'Kiribati': 'Océanie',
    'Marshall Islands': 'Océanie',
    'Micronesia (FS of)': 'Océanie',
    'Nauru': 'Océanie',
    'New Caledonia': 'Océanie',
    'New Zealand': 'Océanie',
    'Palau': 'Océanie',
    'Papua New Guinea': 'Océanie',
    'Samoa': 'Océanie',
    'Solomon Islands': 'Océanie',
    'Tonga': 'Océanie',
    'Tuvalu': 'Océanie',
    'Vanuatu': 'Océanie',
  
    // --- HISTORIQUE ---
    'Czechoslovakia (Former)': 'Historique',
    'Ethiopia (Former)': 'Historique',
    'Former Netherlands Antilles': 'Historique',
    'Sudan (Former)': 'Historique',
    'USSR (Former)': 'Historique',
    'Yemen Arab Republic (Former)': 'Historique',
    'Yemen Democratic (Former)': 'Historique',
    'Yugoslavia (Former)': 'Historique'
  };
  
  export const getContinent = (countryName) => {
    return continentMap[countryName] || 'Historique';
  };